=== santamaria0ee/40260/xml/xml-00.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT direccion (nombrecompleto, correo, telefono, cumple)>
<!ELEMENT nombrecompleto (nombre, apellido)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT correo (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT cumple (dia, mes, anio)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT anio (#PCDATA)>

=== santamaria0ee/40260/xml/xml-00.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE direccion SYSTEM "xml-00.dtd">
<direccion>
    <nombrecompleto>
        <nombre>Isaac</nombre>
        <apellido>santamaria</apellido>
    </nombrecompleto>
    <correo>asjkl@gmail.com</correo>
    <telefono>2203944</telefono>
    <cumple>
        <dia>23</dia>
        <mes>34</mes>
        <anio>7890</anio>
    </cumple>
</diraccion>
